version: '3'
services:
  springboot-app:
    build:
      context: ../golfbooking_be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql-database # Change dependency to the PostgreSQL database service

  react-app:
    build:
      context: ../golfbooking_fe
    ports:
      - "5173:5173"
    depends_on:
      - springboot-app

  postgresql-database: # Define a new service for PostgreSQL
    image: postgres:latest
    container_name: golf-postgresql
    ports:
      - "5432:5432" # Map PostgreSQL's default port 5432 to 5432 on the host
    environment:
      POSTGRES_DB: golfBooking1 # Set the name of the PostgreSQL database
      POSTGRES_USER: George # Set the username for accessing the PostgreSQL database
      POSTGRES_PASSWORD: f9348y8fhe0 # Set the password for the PostgreSQL user
    volumes:
      - postgresql_data:/var/lib/postgresql/data # Mount a volume for PostgreSQL data persistence

volumes:
  postgresql_data:
